### PR TITLE
16 Create Front-End Structure 

### PR DESCRIPTION
**Pull request by Mahmoud-Skafi**
- Create webpack config for development and production environment 
- Add react to the project
- Add prettierrc to the project
- Modify `manifiast.json` 
- Add fonts, global scss 
- Change files/folders structure 
- Create npm scripts for webpack and prettierrc
```json
    "scripts": {
        "build": "webpack --config webpack.prod.js",
        "dev": "webpack --progress --config webpack.dev.js",
        "pretty": "prettier --write \"./**/*.{js,jsx,json,html,scss,css,ts}\""
    },
```

Note how to make prettierrc on save:
just modify/add `vscode.settings` 
```json
{
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        },
        "editor.formatOnSave": true
    },
    "[typescript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true,
            "source.fixAll": true,
            "source.organizeImports": true
        },
        "editor.formatOnSave": true
    },
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        },
        "editor.formatOnSave": true
    },
    "[html]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        },
        "editor.formatOnSave": true
    },
    "[scss]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        },
        "editor.formatOnSave": true
    },
    "compile-hero.disable-compile-files-on-did-save-code": true
}

```

### CODE REVIEW

**Comment by abozanona** [comment]
No need to add `.vscode` files to the pull request. We can include that in the setup guide of the extension.

**Comment by abozanona** [comment]
Executing `npm run dev` results in the following files structure
image

----

 - [ ] The expected behavior for dev environment is not to minify/uglify css/js content. It should only compile ts/scss files.
 - [ ] So many js files are created where we only need 3.
 - [ ] There's only one css file generated. There should be 2 css files generated for content and popup page.

**Comment by abozanona** [comment]
Something nice to have is running prettier action on our github repo to check JS code.  
https://til.simonwillison.net/github-actions/prettier-github-actions

**Comment by Mahmoud-Skafi** [comment]
> No need to add `.vscode` files to the pull request. We can include that in the setup guide of the extension.

I thought it was already in the git ignore

**Comment by Mahmoud-Skafi** [comment]
> Something nice to have is running prettier action on our github repo to check JS code format. https://til.simonwillison.net/github-actions/prettier-github-actions

I will try to make that

**Review by abozanona — APPROVED** [review]

**Review by abozanona — APPROVED** [review]

**Pull request merged**
